name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"
          cache: false # conflicts with the golangci-lint cache

      - name: "golangci-lint"
        uses: "golangci/golangci-lint-action@v3"
        with:
          version: "v1.54"
          args: "--timeout=3m"
