name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-go@v4"
        with:
          go-version: "1.23.0"
          go-version-file: "go.mod"

      - uses: "cardinalby/export-env-action@v2"
        with:
          envFile: ".env"

      - name: "test"
        run: "make docker/test"

      - name: "upload coverage reports to Codecov"
        uses: "codecov/codecov-action@v3"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-go@v4"
        with:
          go-version-file: "go.mod"
          cache: false # conflicts with the golangci-lint cache

      - name: "golangci-lint"
        uses: "golangci/golangci-lint-action@v3"
        with:
          version: "v1.60.3"
          args: "--timeout=3m"
